# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-uk
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: English website title...
  params:
    description: Site description in English...
  


# Uncomment the lines below to configure your website in a second language.
fr:
  languageCode: fr
  contentDir: content/fr
  title: French website title...
  params:
    description: Site description in French...

  # menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
