# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-uk
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: English website title...
  params:
    description: Site description in English...


# Uncomment the lines below to configure your website in a second language.
fr:
  languageCode: fr
  contentDir: content/fr
  title: French website title...
  params:
    description: Site description in French...

  header:
    navbar:
      enable: true
      block: 'navbar'
      fixed_to_top: true
      show_search: false
      show_theme_chooser: false
      highlight_active_link: true
      show_translations: true
      logo:
        text: 'Philippe Neveux'
      button:
        enable: true
        text: "Contactez moi sur LinkedIn"
        url: "https://www.linkedin.com/in/philippe-neveux/"

  # menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
